"""Init

Revision ID: 6383ac736e9a
Revises: 3c51b1a9e0c3
Create Date: 2024-04-23 21:10:58.826764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6383ac736e9a'
down_revision: Union[str, None] = '3c51b1a9e0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_email_key', 'contacts', type_='unique')
    op.drop_constraint('contacts_phone_key', 'contacts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contacts_phone_key', 'contacts', ['phone'])
    op.create_unique_constraint('contacts_email_key', 'contacts', ['email'])
    # ### end Alembic commands ###
